name: Compare outputs

on: [push, pull_request]

jobs:
  compare-outputs:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Compare images
      run: ./scripts/compare-all.ps1
      shell: powershell